# Generated by Django 3.2.4 on 2021-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compny_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=10)),
                ('address', models.TextField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
