# Generated by Django 3.2.4 on 2021-06-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_compny_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='compny_details',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
